hosts:
  - localhost:8091
username: user
password: 123456
bucketName: dcp-test
logging:
  level: info
dcp:
  group:
    name: groupName
redis:
  db: 0
  sentinel:
    masterName: mymaster
    sentinelAddrs:
      - localhost:26379
      - localhost:26380
      - localhost:26381
    password: ""